Source    = \
	GAnnotator.java \
	GCanvas.java \
	GComponent.java \
	GImage.java \
	GInteraction.java \
	GObject.java \
	GPosition.java \
	GPositional.java \
	GScene.java \
	GScrollHandler.java \
	GSegment.java \
	GStyle.java \
	GStyleListener.java \
	GText.java \
	GTransformer.java \
	GViewport.java \
	GWindow.java \
	GWorldExtent.java \
	ZoomInteraction.java \
	TrackCanvas.java \
	SimpleTest.java \

Main = SimpleTest

include $(DEV_HOME)/cc/Makefile
