Source = \
	Box.java \
	Circle.java \
	Disc.java \
	Geometry.java \
	LinearRegression.java \
	Matrix4x4.java \
	Rect.java \
	Region.java \
	Vector4.java \

Main = LinearRegression

include $(DEV_HOME)/cc/Makefile
