Source    = \
	Country.java \
	CountryManager.java \
	Messages_ar_SA.properties \
	Messages_de_DE.properties \
	Messages_en_US.properties \
	Messages_es_ES.properties \
	Messages_fr_FR.properties \
	Messages_hi_IN.properties \
	Messages_ja_JP.properties \
	Messages_no_NO.properties \
	Messages_ru_RU.properties \
	Messages_zh_CN.properties \
	countries.txt \
	synonyms.txt \

Main = CountryManager

include $(DEV_HOME)/cc/Makefile
