Source = \
	ActReader.java \
	FileClipboard.java \
	FileCopy.java \
	FileListener.java \
	FileLock.java \
	FileMonitor.java \
	FileUtil.java \
	GifEncoder.java \
	IoUtil.java \
	Ping.java \
	WebSocket.java \

Main = IoUtil

include $(DEV_HOME)/cc/Makefile
