Source    = \
	Demo1.java \
	Demo1a.java \
#	Demo2.java \
#	Demo3.java \
#	Demo4.java \
#	Demo5.java \
#	Demo6.java \
#	Demo7.java \
#	Demo8.java \
#	Demo9.java \
#	Demo11.java \
#	Demo12.java \
#	Demo13.java \
#	Demo14.java \
#	Demo15.java \
#	Demo16.java \
#	Demo17.java \
#	Demo18.java \
#	Demo19.java \
#	Demo20.java \
#	Demo21.java \
#	Demo23.java \

Main = Demo1a

include $(DEV_HOME)/cc/Makefile

